### ISSUE TITLE
Multi-Focus Image Fusion Training

### ISSUE THREAD

**Issue by Petyooo** [cindydeng1991/TPAMI-CU-Net#4]
Hi!

Thank you for sharing the code that goes along with your great paper. I am working on the multi-focus image fusion problem and I was wondering if you could share the code for blurring and generating patches from the General 100 dataset? I believe the "Step1-get_training_samples_3channel.m" code is for another type of fusion problem.

Thanks,

Peter

**Comment by cindydeng1991** [comment]
Hi Peter，

We have uploaded the generation code in Github.
TPAMI-CU-Net/0-make_multi_focus_images_from DIV2K.py at master ·
cindydeng1991/TPAMI-CU-Net · GitHub
<https://github.com/cindydeng1991/TPAMI-CU-Net/blob/master/Generate_training_data/0-make_multi_focus_images_from%20DIV2K.py>

Best regards,
Xin

**Comment by Petyooo** [comment]
Hi Xin,

Thanks again!!

All the best,

Peter
