### ISSUE TITLE
Pytorch-tensorflow

### ISSUE THREAD

**Issue by AmericaBG** [cindydeng1991/TPAMI-CU-Net#5]
Hi!
First of all, thank you very much for sharing this great job, congratulations!

My question is that in the README you say: "This repository is **Tensorflow** code for our paper entitled ..."
But I only see pytorch code. Is there a tensorflow version?

Thank yoy very much in advance! :)

**Comment by cindydeng1991** [comment]
Sorry，we originally have a tensorflow version, but now we have changed to
Pytorch which is more universal.

**Comment by AmericaBG** [comment]
Ok! 
I'm going to try with Pytorch :) 

Thank you very much!
